import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler


# ---------------------------------------------------------------------------
# Variable role constants (Health Gym schema — Kuo et al. 2022)
# ---------------------------------------------------------------------------

ID_COL       = "PatientID"
TIME_COL     = "Timepoints"
FLUID_COL    = "InputTotal"
VASO_COL     = "MaxVaso"
SURVIVAL_COL = "ReAd"

VITAL_SIGNS   = ["HR", "SysBP", "MeanBP", "DiaBP", "RR", "Temp", "SpO2", "GCS"]
BLOOD_GAS     = ["pH", "BE", "HCO3", "FiO2", "PaO2", "PaCO2", "Lactate"]
ELECTROLYTES  = ["K", "Na", "Cl", "Ca", "IonisedCa", "CO2", "Mg"]
RENAL_HEPATIC = ["BUN", "Creatinine", "Albumin", "SGOT", "SGPT", "TotalBili"]
HEMATO        = ["Hb", "WbcCount", "PlateletsCount", "PTT", "PT", "INR"]
DEMO          = ["Age"]

STATE_COLS = VITAL_SIGNS + BLOOD_GAS + ELECTROLYTES + RENAL_HEPATIC + HEMATO + DEMO


# ---------------------------------------------------------------------------
# 1. Basic cleaning
# ---------------------------------------------------------------------------

def clean_dataframe(df: pd.DataFrame, state_cols: list = None) -> tuple[pd.DataFrame, list]:
    """
    Remove exact duplicates, parasitic columns and constant columns from state space.

    """
    if state_cols is None:
        state_cols = STATE_COLS

    df = df.copy()

    # Remove the parasitic index column generated by some CSV exports
    if "Unnamed: 0" in df.columns:
        df = df.drop(columns=["Unnamed: 0"])

    # Exact duplicates
    n_dup = df.duplicated().sum()
    if n_dup > 0:
        df = df.drop_duplicates()

    # Constant columns in state space (zero variance = no signal)
    existing = [c for c in state_cols if c in df.columns]
    const_cols = [c for c in existing if df[c].nunique() <= 1]
    if const_cols:
        df = df.drop(columns=const_cols)

    state_cols_proc = [c for c in existing if c not in const_cols]

    # Chronological sort by patient
    df = df.sort_values([ID_COL, TIME_COL]).reset_index(drop=True)

    print(f"[clean_dataframe]  Duplicates removed           : {n_dup}")
    print(f"[clean_dataframe]  Constant columns dropped     : {const_cols if const_cols else 'none'}")
    print(f"[clean_dataframe]  Shape after cleaning         : {df.shape}")

    return df, state_cols_proc


# ---------------------------------------------------------------------------
# 2. Missing value imputation
# ---------------------------------------------------------------------------

def impute_missing(
    df: pd.DataFrame,
    state_cols: list,
    thresh_median: float = 0.05,
    thresh_knn: float    = 0.40,
    knn_neighbors: int   = 5,
) -> tuple[pd.DataFrame, list]:
   
    df = df.copy()
    existing = [c for c in state_cols if c in df.columns]
    pct_miss = df[existing].isnull().mean()

    drop_cols = pct_miss[pct_miss > thresh_knn].index.tolist()
    med_cols  = pct_miss[(pct_miss > 0) & (pct_miss <= thresh_median)].index.tolist()
    knn_cols  = pct_miss[(pct_miss > thresh_median) & (pct_miss <= thresh_knn)].index.tolist()

    # Drop columns that are too sparse
    if drop_cols:
        df = df.drop(columns=drop_cols)

    # Median imputation
    for c in med_cols:
        df[c] = df[c].fillna(df[c].median())

    # KNN imputation
    if knn_cols:
        df[knn_cols] = KNNImputer(n_neighbors=knn_neighbors).fit_transform(df[knn_cols])

    state_cols_imp = [c for c in existing if c not in drop_cols]

    remaining_nan = df[state_cols_imp].isnull().sum().sum()
    print(f"[impute_missing]  Dropped (>{thresh_knn*100:.0f}% NaN)      : {drop_cols if drop_cols else 'none'}")
    print(f"[impute_missing]  Median (<{thresh_median*100:.0f}% NaN)    : {med_cols if med_cols else 'none'}")
    print(f"[impute_missing]  KNN ({thresh_median*100:.0f}–{thresh_knn*100:.0f}% NaN)      : {knn_cols if knn_cols else 'none'}")
    print(f"[impute_missing]  Remaining NaNs                      : {remaining_nan}")

    return df, state_cols_imp


# ---------------------------------------------------------------------------
# 3. Outlier clipping (P1–P99)
# ---------------------------------------------------------------------------

def clip_outliers(
    df: pd.DataFrame,
    state_cols: list,
    lower_quantile: float = 0.01,
    upper_quantile: float = 0.99,
) -> tuple[pd.DataFrame, dict]:
    """
    Clip each state variable between its P1 and P99 percentiles.

    """
    df = df.copy()
    clip_bounds = {}
    existing = [c for c in state_cols if c in df.columns]

    for col in existing:
        lo = df[col].quantile(lower_quantile)
        hi = df[col].quantile(upper_quantile)
        clip_bounds[col] = (lo, hi)
        df[col] = df[col].clip(lo, hi)

    print(f"[clip_outliers]  Bounds computed for {len(clip_bounds)} variables (P{lower_quantile*100:.0f}–P{upper_quantile*100:.0f})")

    return df, clip_bounds


def apply_clip_bounds(df: pd.DataFrame, clip_bounds: dict) -> pd.DataFrame:
   
    df = df.copy()
    for col, (lo, hi) in clip_bounds.items():
        if col in df.columns:
            df[col] = df[col].clip(lo, hi)
    return df


# ---------------------------------------------------------------------------
# 4. Normalization
# ---------------------------------------------------------------------------

def normalize_state(
    X: np.ndarray,
    method: str = "minmax",
    scaler=None,
) -> tuple[np.ndarray, object]:
    
    if scaler is None:
        if method == "minmax":
            scaler = MinMaxScaler()
        elif method == "standard":
            scaler = StandardScaler()
        else:
            raise ValueError(f"method must be 'minmax' or 'standard', got: {method!r}")
        X_norm = scaler.fit_transform(X)
    else:
        X_norm = scaler.transform(X)

    print(f"[normalize_state]  Method : {method}  |  Shape : {X_norm.shape}")
    if method == "minmax":
        print(f"[normalize_state]  min={X_norm.min():.4f}  max={X_norm.max():.4f}")
    else:
        print(f"[normalize_state]  mean={X_norm.mean():.6f}  std={X_norm.std():.6f}")

    return X_norm, scaler


# ---------------------------------------------------------------------------
# 5. Full pipeline (high‑level wrapper)
# ---------------------------------------------------------------------------

def full_preprocessing_pipeline(
    df_raw: pd.DataFrame,
    state_cols: list = None,
    normalize: bool  = True,
    norm_method: str = "minmax",
) -> dict:
    """
    Run the complete preprocessing pipeline in a single function:
        clean → impute → clip → normalize

    """
    if state_cols is None:
        state_cols = STATE_COLS

    # Preliminary imputer for normalization (handle remaining NaNs)
    imp_final = SimpleImputer(strategy="median")

    df, sc = clean_dataframe(df_raw, state_cols)
    df, sc = impute_missing(df, sc)
    df, cb = clip_outliers(df, sc)

    X_norm, scaler = None, None
    if normalize:
        X_raw = imp_final.fit_transform(df[sc].values)
        X_norm, scaler = normalize_state(X_raw, method=norm_method)

    return {
        "df"         : df,
        "state_cols" : sc,
        "X_norm"     : X_norm,
        "scaler"     : scaler,
        "clip_bounds": cb,
    }